[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["NODE_OPTIONS='--max-old-space-size=3072' npm run build"]

[start]
cmd = "node --max-old-space-size=400 --expose-gc .next/standalone/server.js"
