-- Add search_plan column to feeds for AI-generated query plans
-- Stores the SearchPlan JSON generated by prompt-intelligence.ts
-- Generated once per feed creation, reused every scan cycle
alter table public.feeds add column if not exists search_plan jsonb;
